name: Testcontainers End-to-End Testing

on:
  push:
    branches:
      - main

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Build Lambda
        run: mvn clean package -DskipTests

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and test with Maven
        env:
          LOCALSTACK_AUTH_KEY: ${{ secrets.LOCALSTACK_AUTH_KEY }}
        run: mvn test